apiVersion: v2
name: event-exporter-app
description: The Event Exporter runs on management clusters to watch and act upon Kubernetes events.
version: 3.5.0
appVersion: 2.2.0
home: https://github.com/giantswarm/event-exporter-app
icon: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
annotations:
  application.giantswarm.io/team: tenet
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/k8s-initiator/1/dark.svg
